### PR TITLE
Fix missing py dependency

### LINKED ISSUE #11: missing dependency on py
`pytest-travis-fold` is depending on `py` package, however the latter isn't listed explicitly as a dependency in setup.cfg. This leads to errors when using `pytest-travis-fold` with recent versions of `pytest`(e.g. `7.2.0`, which dropped `py` as a dependency, thus exposing the problem with `pytest-travis-fold`.
### steps to reproduce:
1. In a clean python installation(with e.g. venv or virtualenv) install `pytest-travis-fold` with `pip`.
```
pip install pytest-travis-fold
```
2. Try to import `pytest-travis-fold`.
```
python -c "import pytest_travis_fold"
```
### expected output:
The modules gets imported successfully without error messages.
### actual output:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mel-afifi/pytest-travis-fold/pytest_travis_fold.py", line 16, in <module>
    from py.builtin import _basestring
ModuleNotFoundError: No module named 'py.builtin'; 'py' is not a package
```

### PR DESCRIPTION
**Pull request by MSK61**
Fixes #11.

### CODE REVIEW

**Comment by The-Compiler** [comment]
I'd heavily suggest dropping the dependency instead, by simply using `str` in place of `_basestrimg` and dropping Python 2 support.

**Comment by abusalimov** [comment]
Hey Florian @The-Compiler,
What would you say about taking over this repository? I realize that I'm not really involved into pytest development anymore, and I'd gladly give away this plugin into loving hands.

**Comment by MSK61** [comment]
@The-Compiler Please feel free to do it, as I'm not knowledgeable enough if tests should be modified/added for this change.

**Comment by The-Compiler** [comment]
@abusalimov I'm afraid I'm not using Travis anymore ever since 2020 when they [pulled some weird shit](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) and everyone, me included, moved to GitHub Actions. So I'll have to pass.

@MSK61 There should be no test changes needed. All `py.builtin._basestring` is is an alias to `str` on Python 3, or `unicode` on Python 2.

**Comment by abusalimov** [comment]
Thanks @MSK61!

**Pull request merged**
