### PR TITLE
Revisit Travis/tox config

### PR DESCRIPTION
**Pull request by blueyed**
This adds a job to test against pytest<3.3 explicitly.

### CODE REVIEW

**Comment by The-Compiler** [comment]
Why keep testing Python 2.6 at all?

**Comment by blueyed** [comment]
@abusalimov 
Do you agree to remove it?

**Comment by blueyed** [comment]
At least we can see here now that the job with pytest < 3.3 works, while the others fail.
Can be moved to some other py version, of course.

**Comment by abusalimov** [comment]
@blueyed @The-Compiler I'm OK with dropping py26 completely.

**Comment by blueyed** [comment]
Same for py32 I guess?
https://travis-ci.org/abusalimov/pytest-travis-fold/jobs/308970828#L474

**Comment by abusalimov** [comment]
@blueyed Sure, let's remove it!

**Comment by abusalimov** [comment]
@blueyed thanks for the awesome work on #4, #5 and #6! I'm gonna tag and release 1.3.0 including your fixes now.

**Comment by blueyed** [comment]
Nice, you're welcome!

**Pull request merged**
